apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: shbooks
  artifacts:
    # - image: us.gcr.io/shbooks/auth
    - image: beretedocker/shbooks/auth
      context: services/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
    # - image: us.gcr.io/shbooks/catalog
    - image: beretedocker/shbooks/catalog
      context: services/catalog
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
    # - image: us.gcr.io/shbooks/frontend
    - image: beretedocker/shbooks/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
          - dest: .
            src: src/**/*.tsx