name: auth:ci
on:
  pull_request:
    paths: 
      - services/auth/**
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/auth && npm ci && npm run ci-test
